### ISSUE TITLE
crash on inputting 2^12 byte long inputs

### ISSUE THREAD

**Issue by weber-martin** [racket/xrepl#11]
pasting this into a racket v7.3 session with its xrepl:
```
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
```
will trigger:
`SIGSEGV MAPERR si_code 1 fault on addr (nil)
Aborted`

This is coming from libedit; not sure whether xrepl can set it up to have, say, slightly more memory? Or whether it's a non-issue practically. Still, was surprising to see that.

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fd7e84eb535 in __GI_abort () at abort.c:79
#2  0x000000000066fb19 in fault_handler ()
#3  <signal handler called>
#4  0x00007fd7ddb99d00 in ?? () from /usr/lib/x86_64-linux-gnu/libedit.so.2
#5  0x00007fd7ddb9b353 in ?? () from /usr/lib/x86_64-linux-gnu/libedit.so.2
#6  0x00007fd7ddb92d02 in ?? () from /usr/lib/x86_64-linux-gnu/libedit.so.2
#7  0x00007fd7ddb99792 in el_wgets () from /usr/lib/x86_64-linux-gnu/libedit.so.2
#8  0x00007fd7ddb94dc3 in el_gets () from /usr/lib/x86_64-linux-gnu/libedit.so.2
#9  0x00007fd7ddba74f6 in readline () from /usr/lib/x86_64-linux-gnu/libedit.so.2
#10 0x000000000066d328 in ffi_call_unix64 ()
#11 0x000000000066ccef in ffi_call ()
#12 0x000000000066673f in ?? ()
#13 0x0000000000666c27 in ?? ()
#14 0x00007fd7e8858bf2 in ?? ()
#15 0x00007fff42e04488 in ?? ()
#16 0x00007fd7dda5b158 in ?? ()
#17 0x00007fff42e044a0 in ?? ()
#18 0xfffffffffffff430 in ?? ()
#19 0x00007fff42e044e8 in ?? ()
#20 0x00007fff42e04580 in ?? ()
#21 0x0000000000000001 in ?? ()
#22 0x0000000000000000 in ?? ()
```

**Comment by maueroats** [comment]
Not reproducible in 8.15
